-- cstmeat.csv の a〜t 列用テーブル作成
-- テーブル名: cstmeat
-- カラム: cstmeat（主キー）、info00 〜 info19（a〜t の20列）、すべて text 型

CREATE TABLE cstmeat (
    cstmeatid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info00 text,
    info01 text,
    info02 text,
    info03 text,
    info04 text,
    info05 text,
    info06 text,
    info07 text,
    info08 text,
    info09 text,
    info10 text,
    info11 text,
    info12 text,
    info13 text,
    info14 text,
    info15 text,
    info16 text,
    info17 text,
    info18 text,
    info19 text,
    info20 text,
    info21 text,
);